### ISSUE TITLE
Suggestion: use version numbers synchronize with ESLint's

### ISSUE THREAD

**Issue by cssmagic** [wintercounter/eslint-global-patch#1]
For example, if the current version of `eslint-global-patch` suits `eslint@6.6.6`, then mark it as `eslint-global-patch@6.6.6`.

Then users will be confident to use `eslint-global-patch@6.6.6` with `eslint@6.6.6`, or simply use `eslint-global-patch@6.x` with `eslint@6.x` in their `package.json` files.

In case ESLint upgrades to v7, version numbers could remind users that they should wait for `eslint-global-patch@7`.

---

Thanks to this tool which saves our CI program. 👍

**Comment by wintercounter** [comment]
I was thinking this before but I just didn't want to release a new one every time there is a new ESLint version. However, it's a good idea to follow at least the main version. I'll do that on the next update.

**Comment by cssmagic** [comment]
Thanks!
