### ISSUE TITLE
Regarding eslint@8

### ISSUE THREAD

**Issue by kurtextrem** [wintercounter/eslint-global-patch#2]
The file needed to modify is now eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

**Comment by wintercounter** [comment]
I added the file to the list. I myself couldn't test ESLint 8 completely, the ecosystem is just not there yet, for example, v8 support from @eslint/babel-parser is a must for me to work. Let's hope it'll work for you guys in your case. Version is 8.1.1.

**Comment by kurtextrem** [comment]
At least for me babel-parser seems to be working in VSCode in my config after applying the global patch
